### ISSUE TITLE
Task list

### ISSUE THREAD

**Issue by EvanTrvs** [EvanTrvs/Jeu_de_Hex#2]
Here's a To Do List : 

- [x] Bot : Détection de victoire
- [x] Bot : Gagne la partie quand la victoire est détecté
- [x] Fonction de fin de partie
- [x] Terminer les minuteurs
- [x] Ranger et organiser le menu principale et les paramètre en fonction
